# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BrowseOverflow' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for BrowseOverflow

  target 'BrowseOverflowTests' do
    inherit! :search_paths
    pod 'OCMock', '~> 3.4'
  end

  target 'BrowseOverflowUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
